In [1]:
import math
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("mlsheet.csv")

In [3]:
df.head(4)

,timestamp,open,high,low,close,volume,close_p1,close_p2,close_p3,close_p4,close_p5,close_p6,close_p7,close_p8,close_p9,close_p10,close_p11
0,2017-01-02 09:15:00+05:30,80.83,81.00,80.83,80.90,29495,80.90,80.80,80.77,80.60,80.57,80.53,80.73,80.77,80.77,80.90,81.20
1,2017-01-02 09:16:00+05:30,80.90,80.90,80.77,80.90,25445,80.80,80.77,80.60,80.57,80.53,80.73,80.77,80.77,80.90,81.20,81.13
2,2017-01-02 09:17:00+05:30,80.87,80.93,80.77,80.80,23282,80.77,80.60,80.57,80.53,80.73,80.77,80.77,80.90,81.20,81.13,81.10
3,2017-01-02 09:18:00+05:30,80.80,80.80,80.67,80.77,31247,80.60,80.57,80.53,80.73,80.77,80.77,80.90,81.20,81.13,81.10,81.00

In [4]:
x = df.iloc[:,0:6]
y = df.iloc[:,6:]
y

,close_p1,close_p2,close_p3,close_p4,close_p5,close_p6,close_p7,close_p8,close_p9,close_p10,close_p11
0,80.90,80.80,80.77,80.60,80.57,80.53,80.73,80.77,80.77,80.90,81.20
1,80.80,80.77,80.60,80.57,80.53,80.73,80.77,80.77,80.90,81.20,81.13
2,80.77,80.60,80.57,80.53,80.73,80.77,80.77,80.90,81.20,81.13,81.10
3,80.60,80.57,80.53,80.73,80.77,80.77,80.90,81.20,81.13,81.10,81.00
4,80.57,80.53,80.73,80.77,80.77,80.90,81.20,81.13,81.10,81.00,80.93
...,...,...,...,...,...,...,...,...,...,...,...
2983,85.87,85.87,85.80,85.77,85.77,85.77,85.73,85.67,85.60,85.67,85.60
2984,85.87,85.80,85.77,85.77,85.77,85.73,85.67,85.60,85.67,85.60,85.53
2985,85.80,85.77,85.77,85.77,85.73,85.67,85.60,85.67,85.60,85.53,85.53
2986,85.77,85.77,85.77,85.73,85.67,85.60,85.67,85.60,85.53,85.53,85.53
2987,85.77,85.77,85.73,85.67,85.60,85.67,85.60,85.53,85.53,85.53,85.60

In [4]:
from sklearn.model_selection import train_test_split
x_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.33, random_state=42)

NameError: name 'x_train' is not defined

In [7]:
model = Sequential()
model.add(LSTM(units=50, return_sequences=True,input_shape=(x_train.shape[1],1)))
model.add(LSTM(units=50, return_sequences=False))
model.add(Dense(units=25))
model.add(Dense(units=11))
model.compile(optimizer='adam', loss='mean_squared_error')

In [8]:
model.fit(x_train, y_train, batch_size=124, epochs=1)

ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).